# Generated by Django 3.2.4 on 2021-07-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Citizen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Citizen')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname')),
                ('lastName', models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname')),
                ('citizen_img', models.ImageField(upload_to='citizen_img')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('origin_address', models.TextField(blank=True, null=True)),
                ('origin_tambon', models.CharField(blank=True, max_length=50, null=True, verbose_name='origin_tambon')),
                ('origin_distrinct', models.CharField(blank=True, max_length=50, null=True, verbose_name='origin_distrinct')),
                ('origin_province', models.CharField(blank=True, max_length=50, null=True, verbose_name='origin_province')),
                ('is_foreigner', models.CharField(blank=True, max_length=1, null=True, verbose_name='is_foreigner')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('destination_tambon', models.CharField(blank=True, max_length=50, null=True, verbose_name='destination_tambon')),
                ('destination_distrinct', models.CharField(blank=True, max_length=50, null=True, verbose_name='destination_distrinct')),
                ('destination_province', models.CharField(blank=True, max_length=50, null=True, verbose_name='destination_province')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
    ]
