# Generated by Django 3.2.4 on 2021-07-03 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_citizen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='origin_address',
        ),
        migrations.AddField(
            model_name='citizen',
            name='dates_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='dates_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='vehicle',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='vehicle'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='firstName'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='lastName'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
    ]
