# Generated by Django 3.2.4 on 2021-07-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20210703_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='description',
        ),
    ]
