# Generated by Django 3.2.4 on 2021-07-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_remove_citizen_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='Citizen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='citizen'),
        ),
    ]
