# Generated by Django 3.2.4 on 2021-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0005_alter_citizen_citizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='Citizen',
        ),
        migrations.AddField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='citizen'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='firstName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='firstName'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='lastName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='lastName'),
        ),
    ]
