# Generated by Django 3.2.4 on 2021-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0006_auto_20210703_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='preName',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='preName'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='sex'),
        ),
    ]
