# Generated by Django 3.2.4 on 2021-07-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0007_auto_20210703_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='citizen_id'),
        ),
        migrations.AlterModelTable(
            name='citizen',
            table='citizens',
        ),
    ]
