# Generated by Django 3.2.4 on 2021-07-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0010_citizen_citizen_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='is_foreigner',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='is_foreigner'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sex'),
        ),
    ]
